Fix bug in dual of PSDConeSquare bridge
jump-dev/MathOptInterface.jl pull request #1839
Opened 2022-05-12 02:05 UTC by odow

Closes #1830

If there are no symmetry constraints added, then we can copy-across the duals from the upper triangle to the lower triangle.

2022-05-12 07:18 UTC, blegat requested changes
If you want the dual of the `PSDConeTriangle`, you should use this set, not `PSDConeSquare`.
The user should have used that. If you want some detection of symmetric even if the user didn't specify that, that would be at the JuMP level because at the MOI level, `PSDConeSquare` was explicitly given. At the JuMP level, the user wasn't explicit in `@constraint(...)` so we could argue choosing something for him there.

2022-05-12 08:20 UTC, odow commented
So JuMP should error for the dual of a square PSD constraint? I don't quite follow. I don't see why it should return different duals for `Triangle` and `Square`.

2022-05-16 15:22 UTC, blegat commented
Okay so there are two cases:
1) The lower and upper triangular entries are symbolically the same. In that case, we use the upper triangular but since they are the same, it could as well be the lower triangular. So we can give `tri[k]` for each dual as you suggest in this PR.
2) The lower and upper triangular entries are different. In that case, we do what is currently done.

To implement this efficiently, iterate over the entries in the same order than `bridge_constraint`. That way, you will have a running index with the next entry in `sym` that you will run into and you can just check if you are in an entry with a symmetrization constraint in O(1).

2022-05-16 21:15 UTC, odow commented
How is what I've done different from what you're suggesting?

2022-05-19 05:22 UTC, blegat commented
I suggest to do that entrywise. If there is one symmetrization constrain for one entry, it shouldn't affect other entries

2022-05-19 05:31 UTC, odow commented
Oh,
```Julia
julia> using JuMP, SCS

julia> model = Model(SCS.Optimizer)
A JuMP Model
Feasibility problem with:
Variables: 0
Model mode: AUTOMATIC
CachingOptimizer state: EMPTY_OPTIMIZER
Solver name: SCS

julia> @variable(model, X[1:2, 1:2] >= 0)
2×2 Matrix{VariableRef}:
 X[1,1]  X[1,2]
 X[2,1]  X[2,2]

julia> @variable(model, z[1:2] >= 0)
2-element Vector{VariableRef}:
 z[1]
 z[2]

julia> Y = [
           X[1, 1] X[1, 2] 0;
           X[1, 2] X[2, 2] z[1];
           0       z[2]    0;
       ]
3×3 Matrix{AffExpr}:
 X[1,1]  X[1,2]  0
 X[1,2]  X[2,2]  z[1]
 0       z[2]    0

julia> c = @constraint(model, Y >= 0, PSDCone())
[X[1,1]  X[1,2]  0;
 X[1,2]  X[2,2]  z[1]; ∈ PSDCone()
 0       z[2]    0]

julia> @objective(model, Min, sum(X) + sum(z))
X[1,1] + X[2,1] + X[1,2] + X[2,2] + z[1] + z[2]

julia> optimize!(model)
------------------------------------------------------------------
	       SCS v3.2.0 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
------------------------------------------------------------------
problem:  variables n: 6, constraints m: 13
cones: 	  z: primal zero / dual free vars: 1
	  l: linear vars: 6
	  s: psd vars: 6, ssize: 1
settings: eps_abs: 1.0e-04, eps_rel: 1.0e-04, eps_infeas: 1.0e-07
	  alpha: 1.50, scale: 1.00e-01, adaptive_scale: 1
	  max_iters: 100000, normalize: 1, rho_x: 1.00e-06
	  acceleration_lookback: 10, acceleration_interval: 10
lin-sys:  sparse-direct
	  nnz(A): 12, nnz(P): 0
------------------------------------------------------------------
 iter | pri res | dua res |   gap   |   obj   |  scale  | time (s)
------------------------------------------------------------------
     0| 2.00e+01  1.19e+00  6.09e+01 -3.05e+01  1.00e-01  2.95e-05 
    25| 7.61e-06  3.50e-08  1.25e-05  6.25e-06  1.00e-01  9.54e-05 
------------------------------------------------------------------
status:  solved
timings: total: 1.68e-04s = setup: 7.03e-05s + solve: 9.76e-05s
	 lin-sys: 7.14e-06s, cones: 5.72e-05s, accel: 1.51e-06s
------------------------------------------------------------------
objective = 0.000006
------------------------------------------------------------------

julia> dual(c)
3×3 Matrix{Float64}:
 0.548333  0.561184  0.234482
 0.0       0.634157  0.206683
 0.0       0.438467  0.493305
```

That's just messed up as a return value...

2022-05-20 02:17 UTC, odow commented
Is this what you meant? 

I guess I don't really get what the dual of a non-symmetric matrix is meant to be. Telling users that it is `A + A^T` is confusing.
```Julia
julia> using JuMP, SCS, LinearAlgebra

julia> function foo(flag)
           model = Model(SCS.Optimizer)
           set_silent(model)
           @variable(model, X[1:3, 1:3], Symmetric)
           @variable(model, z[1:3] >= 0)
           Y = [1 z'; z X]
           if flag
               Y = LinearAlgebra.Symmetric(Y)
           end
           c = @constraint(model, Y >= 0, PSDCone())
           @objective(model, Min, sum(X) + sum(z))
           optimize!(model)
           return dual(c)
       end
foo (generic function with 2 methods)

julia> foo(true)
4×4 Symmetric{Float64, Matrix{Float64}}:
 1.20006e-9  3.46419e-5  3.46419e-5  3.46419e-5
 3.46419e-5  1.0         1.0         1.0
 3.46419e-5  1.0         1.0         1.0
 3.46419e-5  1.0         1.0         1.0

julia> foo(false)
4×4 Matrix{Float64}:
 1.20006e-9  3.46419e-5  3.46419e-5  3.46419e-5
 3.46419e-5  1.0         1.0         1.0
 3.46419e-5  1.0         1.0         1.0
 3.46419e-5  1.0         1.0         1.0

julia> function bar(flag)
           model = Model(SCS.Optimizer)
           set_silent(model)
           @variable(model, X[1:3, 1:3] >= 0)
           @variable(model, z[1:3] >= 0)
           Y = [1 z'; z X]
           if flag
               Y = LinearAlgebra.Symmetric(Y)
           end
           c = @constraint(model, Y >= 0, PSDCone())
           @objective(model, Min, sum(X) + sum(z))
           optimize!(model)
           return dual(c)
       end
bar (generic function with 1 method)

julia> bar(true)
4×4 Symmetric{Float64, Matrix{Float64}}:
 2.07224e-15  2.77064e-8  2.77064e-8  2.77064e-8
 2.77064e-8   0.494408    0.304416    0.304416
 2.77064e-8   0.304416    0.494408    0.304416
 2.77064e-8   0.304416    0.304416    0.494408

julia> bar(false)
4×4 Matrix{Float64}:
 1.93821e-13  2.97454e-7  2.97454e-7  2.97454e-7
 2.97454e-7   0.486689    0.348128    0.348128
 2.97454e-7   0.538354    0.486689    0.348128
 2.97454e-7   0.538354    0.538354    0.486689
```

Note how the dual is not symmetric, so the matrix is not PSD, but `b = bar(false); b + b'` is.

2022-05-26 20:24 UTC, odow commented
I need to take another look at this.

2022-05-26 23:19 UTC, odow commented
Here's what we currently get:
```Julia
julia> function foo(flag)
           model = Model(SCS.Optimizer)
           set_silent(model)
           @variable(model, X[1:3, 1:3] >= 0, Symmetric)
           @variable(model, z[1:3] >= 0)
           Y = [1 z'; z X]
           if flag
               Y = LinearAlgebra.Symmetric(Y)
           end
           c = @constraint(model, Y >= 0, PSDCone())
           @objective(model, Min, sum(X) + sum(z))
           optimize!(model)
           return dual(c)
       end
foo (generic function with 1 method)

julia> foo(true)
4×4 Symmetric{Float64, Matrix{Float64}}:
 5.41877e-14  1.7125e-7  1.7125e-7  1.7125e-7
 1.7125e-7    0.59482    0.515269   0.515269
 1.7125e-7    0.515269   0.59482    0.515269
 1.7125e-7    0.515269   0.515269   0.59482

julia> foo(false)
4×4 Matrix{Float64}:
 5.41877e-14  3.425e-7  3.425e-7  3.425e-7
 0.0          0.59482   1.03054   1.03054
 0.0          0.0       0.59482   1.03054
 0.0          0.0       0.0       0.59482

julia> function bar(flag)
           model = Model(SCS.Optimizer)
           set_silent(model)
           @variable(model, X[1:3, 1:3] >= 0)
           @variable(model, z[1:3] >= 0)
           Y = [1 z'; z X]
           if flag
               Y = LinearAlgebra.Symmetric(Y)
           end
           c = @constraint(model, Y >= 0, PSDCone())
           @objective(model, Min, sum(X) + sum(z))
           optimize!(model)
           return dual(c)
       end
bar (generic function with 1 method)

julia> bar(true)
4×4 Symmetric{Float64, Matrix{Float64}}:
 2.07224e-15  2.77064e-8  2.77064e-8  2.77064e-8
 2.77064e-8   0.494408    0.304416    0.304416
 2.77064e-8   0.304416    0.494408    0.304416
 2.77064e-8   0.304416    0.304416    0.494408

julia> bar(false)
4×4 Matrix{Float64}:
 1.93821e-13  5.94908e-7  5.94908e-7  5.94908e-7
 0.0          0.486689    0.348128    0.348128
 0.0          0.538354    0.486689    0.348128
 0.0          0.538354    0.538354    0.486689

(dual) pkg> st
      Status `/private/tmp/dual/Project.toml`
  [4076af6c] JuMP v1.1.0
  [c946c3f1] SCS v1.1.2
  [37e2e46d] LinearAlgebra
```

Here's this PR
```Julia
julia> using JuMP, SCS, LinearAlgebra

julia> function foo(flag)
           model = Model(SCS.Optimizer)
           set_silent(model)
           @variable(model, X[1:3, 1:3] >= 0, Symmetric)
           @variable(model, z[1:3] >= 0)
           Y = [1 z'; z X]
           if flag
               Y = LinearAlgebra.Symmetric(Y)
           end
           c = @constraint(model, Y >= 0, PSDCone())
           @objective(model, Min, sum(X) + sum(z))
           optimize!(model)
           return dual(c)
       end
foo (generic function with 1 method)

julia> foo(true)
4×4 Symmetric{Float64, Matrix{Float64}}:
 5.41877e-14  1.7125e-7  1.7125e-7  1.7125e-7
 1.7125e-7    0.59482    0.515269   0.515269
 1.7125e-7    0.515269   0.59482    0.515269
 1.7125e-7    0.515269   0.515269   0.59482

julia> foo(false)
4×4 Matrix{Float64}:
 5.41877e-14  1.7125e-7  1.7125e-7  1.7125e-7
 1.7125e-7    0.59482    0.515269   0.515269
 1.7125e-7    0.515269   0.59482    0.515269
 1.7125e-7    0.515269   0.515269   0.59482

julia> function bar(flag)
           model = Model(SCS.Optimizer)
           set_silent(model)
           @variable(model, X[1:3, 1:3] >= 0)
           @variable(model, z[1:3] >= 0)
           Y = [1 z'; z X]
           if flag
               Y = LinearAlgebra.Symmetric(Y)
           end
           c = @constraint(model, Y >= 0, PSDCone())
           @objective(model, Min, sum(X) + sum(z))
           optimize!(model)
           return dual(c)
       end
bar (generic function with 1 method)

julia> bar(true)
4×4 Symmetric{Float64, Matrix{Float64}}:
 2.07224e-15  2.77064e-8  2.77064e-8  2.77064e-8
 2.77064e-8   0.494408    0.304416    0.304416
 2.77064e-8   0.304416    0.494408    0.304416
 2.77064e-8   0.304416    0.304416    0.494408

julia> bar(false)
4×4 Matrix{Float64}:
 1.93821e-13  2.97454e-7  2.97454e-7  2.97454e-7
 2.97454e-7   0.486689    0.348128    0.348128
 2.97454e-7   0.538354    0.486689    0.348128
 2.97454e-7   0.538354    0.538354    0.486689

(dual2) pkg> st
      Status `/private/tmp/dual2/Project.toml`
  [4076af6c] JuMP v1.1.0
  [b8f27783] MathOptInterface v1.2.0 `https://github.com/jump-dev/MathOptInterface.jl.git#od/fix-square-dual`
  [c946c3f1] SCS v1.1.2
  [37e2e46d] LinearAlgebra
```

So I think this is a win in that if you pass a symbolically symmetric matrix, you now get the correct value back, in the sense that `foo(true)` and `foo(false)` return the same dual. The previous behavior of returning an upper triangular was weird.
It's also non-breaking in the sense that if someone was using `A = dual(c)`, `C = 0.5 * (A + A')`, then they still get the same dual.

In the second case, passing a non-symmetric matrix, it's weird, but we keep the same behavior.

2022-06-10 09:22 UTC, blegat commented
I implemented what I described in https://github.com/jump-dev/MathOptInterface.jl/pull/1839#issuecomment-1127810447, let me know what you think

2022-06-12 21:17 UTC, odow commented
That's what I had, just in one loop instead of two. I fixed the formatting and added the equality constraint to the duality discussion.

2022-06-13 06:31 UTC, blegat commented
> That's what I had, just in one loop instead of two.

I must have misread then, I thought you still had the previous implementation

2022-06-13 06:32 UTC, blegat approved these changes

2022-06-13 08:06 UTC, merged