Prep for v1.20.1
jump-dev/MathOptInterface.jl pull request #2288
Opened 2023-09-21 22:26 UTC by odow

## TODO

 - [ ] #2285

## Basic

 - [ ] `version` field of `Project.toml` has been updated
       - If a breaking change, increment the MAJOR field and reset others to 0
       - If adding new features, increment the MINOR field and reset PATCH to 0
       - If adding bug fixes or documentation changes, increment the PATCH field

## Documentation

 - [ ] Add a new entry to `docs/src/changelog.md`, following existing style

## Tests

 - [ ] The `solver-tests.yml` GitHub action does not have unexpected failures.
       To run the action, go to:
       https://github.com/jump-dev/MathOptInterface.jl/actions/workflows/solver-tests.yml
       and click "Run workflow"

2023-09-21 22:50 UTC, odow commented on docs/src/changelog.md
> + - Fixed `MethodError` when trying to modify a variable objective (#2278)
```suggestion
 - Fixed `MethodError` when trying to modify a variable objective (#2278)
 - Fixed stack-overflow in `Utilities.operate(+,...)` with many arguments (#2285)
```

2023-09-21 23:17 UTC, odow commented on docs/src/changelog.md
> +   - Removed unecessary `const` acronyms in `Utilities` (#2280) (#2281)
```suggestion
   - Removed unnecessary `const` acronyms in `Utilities` (#2280) (#2281)
```

2023-09-22 02:06 UTC, odow commented on docs/src/changelog.md
> + - Fixed various JET errors (#2267) (#2269) (#2270) (#2271) (#2276) (#2277)
```suggestion
 - Fixed various JET errors (#2267) (#2269) (#2270) (#2271) (#2276) (#2277) (#2289)
```

2023-09-22 07:32 UTC, blegat requested changes
Let's hold off until my concern in https://github.com/jump-dev/MathOptInterface.jl/issues/2284 is addressed, I think we should revert https://github.com/jump-dev/MathOptInterface.jl/pull/2285 as it might cause more issues by fixing an invalid use case

2023-09-22 11:07 UTC, odow commented on docs/src/changelog.md
> +   - Removed invalid and unused method (#2286)
```suggestion
   - Removed invalid and unused method (#2286)
 - Refactored `src/Utilities/model.jl` (#2287)
```

2023-09-23 07:17 UTC, blegat approved these changes
We can release, the benchmark of https://github.com/jump-dev/MathOptInterface.jl/issues/2284#issuecomment-1732136438 shows there is no regression

2023-09-24 02:35 UTC, odow commented on docs/src/changelog.md
> +## v1.20.1 (September 22, 2023)
```suggestion
## v1.20.1 (September 24, 2023)
```

2023-09-24 02:35 UTC, odow commented on docs/src/changelog.md
> + - Fixed stack-overflow in `Utilities.operate(+,...)` with many arguments (#2285)
```suggestion
 - Fixed stack-overflow in `Utilities.operate(+,...)` with many arguments (#2285) (#2290)
```

2023-09-24 03:41 UTC, merged