Prep for v1.27.2
jump-dev/MathOptInterface.jl pull request #2471
Opened 2024-04-08 22:14 UTC by odow

## TODO

 - [ ] #2470

## Basic

 - [x] `version` field of `Project.toml` has been updated
       - If a breaking change, increment the MAJOR field and reset others to 0
       - If adding new features, increment the MINOR field and reset PATCH to 0
       - If adding bug fixes or documentation changes, increment the PATCH field

## Documentation

 - [x] Add a new entry to `docs/src/changelog.md`, following existing style

## Tests

 - [ ] The `solver-tests.yml` GitHub action does not have unexpected failures.
       To run the action, go to:
       https://github.com/jump-dev/MathOptInterface.jl/actions/workflows/solver-tests.yml
       and click "Run workflow"

2024-04-09 07:50 UTC, blegat requested changes
We first need to decide what to do with https://github.com/jump-dev/MathOptInterface.jl/pull/2468. See https://github.com/jump-dev/MathOptInterface.jl/issues/2450#issuecomment-2044302953

2024-04-11 05:15 UTC, odow commented on Project.toml
> +version = "1.27.2"
```suggestion
version = "1.28.0"
```

2024-04-11 05:15 UTC, odow commented on docs/src/changelog.md
> +## v1.27.2 (April 11, 2024)
```suggestion
## v1.28.0 (April 11, 2024)
```

2024-04-11 06:38 UTC, odow commented on docs/src/changelog.md
> +   functions (#2468)
```suggestion
   functions (#2468) (#2475)
```

2024-04-11 09:10 UTC, blegat approved these changes

2024-04-11 09:13 UTC, merged